name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change file mode
      run: chmod +x pizero.sh
    - name: Run the script
      run: ./pizero.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: Artifact_Upload
        path: raspberrypi/tmp/deploy/images/raspberrypi0-wifi/core-image-base-raspberrypi0-wifi.sdimg
